### ISSUE TITLE
Why not extract IPv4.ml?

### ISSUE THREAD

**Issue by danna2019** [cornell-netlab/sigcomm21-tutorial#1]
Once 'make' under repo-dir, ACL.ml extracted and appears on ./coq/extraction/, but IPv4.ml didn't extract and doesn't appear on ./coq/extraction/.

How can I handle it?

**Comment by jnfoster** [comment]
Edit `coq/extraction/Extract.v` to have these lines,
```
Cd "extraction".
Separate Extraction Syntax Interp ACL IPv4.
Cd "..".
```
then you'll get an `IPv4.ml` file in the `extraction` directory.

**Comment by danna2019** [comment]
Thx.
